### ISSUE TITLE
falsely complains "The slow query log is NOT enabled."

### ISSUE THREAD

**Issue by otheus** [BMDan/tuning-primer.sh#11] opened 2020-03-04 09:33 UTC
primer version:
`#       Version: 1.99           Released: 2018-06-10                    #`

MySQL Version:
`MySQL Version 5.7.25-log x86_64`

Warning message (incorrect?):
`The slow query log is NOT enabled.
Current long_query_time = 2.000000 sec.
`

my.cnf:
`~$ grep slow /etc/my.cnf
slow_query_log=1
slow_query_log_file=/var/log/mysql/slowqueries.log
`

The code indicates it is reading the my.cnf file and looking for a boolean (ON or OFF). This is incorrect behavior. The correct  implementation would use `mysqladmin variables` .

**Comment by otheus** [comment] 2020-03-04 09:39
The implementation in `check_slow_queries` is incorrect. It first uses the mysql-variable method, but then overrides these determinations with checks to my.cnf without first checking if it is needed.
Perhaps this is version=specific?

Current:
`
        mysql_variable \'log%queries\' log_slow_queries
`

Correct (for my version):
`        mysql_variable \'slow_query_log\' log_slow_queries
`

**Comment by BMDan** [comment] 2020-04-05 05:45
Thanks for the investigation!  You're absolutely right, but as this is ultimately the same issue mentioned in #10, and #10 was opened first, I'm going to close this one in favor of that one.  Regardless, fix incoming momentarily.

Duplicate of #10

**Closed** 2020-04-05 05:45 UTC
